In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
data=pd.read_csv('car_age_price.csv')

In [3]:
data.head()

Year   Price
0  2018  465000
1  2019  755000
2  2019  700000
3  2018  465000
4  2018  465000

In [6]:
data.shape

(112, 2)

In [5]:
data.isnull().sum()

Year     0
Price    0
dtype: int64

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    112 non-null    int64
 1   Price   112 non-null    int64
dtypes: int64(2)
memory usage: 1.9 KB


In [10]:
y= data['Price']
x=data.drop('Price',axis=1)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

# Linear Regression

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
lr=LinearRegression()
model=lr.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [23]:
y_pred

array([600775.91252081, 505558.77690466, 553167.34471273, 553167.34471273,
       553167.34471273, 410341.6412885 , 505558.77690466, 553167.34471273,
       600775.91252081, 600775.91252081, 315124.50567235, 505558.77690466,
       410341.6412885 , 648384.48032889, 553167.34471273, 600775.91252081,
       315124.50567235, 410341.6412885 , 505558.77690466, 505558.77690466,
       505558.77690466, 505558.77690466, 505558.77690466])

In [15]:
from sklearn.metrics import mean_squared_error,r2_score

In [16]:
print('MSE is:',mean_squared_error(y_test,y_pred))
print('R squared value is:',r2_score(y_test,y_pred))

MSE is: 4326906256.829671
R squared value is: 0.36759313425902185


In [17]:
#prdicting the possible price of a 2022
x_2022= pd.DataFrame([2022],columns=['Year'])
ypred2022=model.predict(x_2022)

In [18]:
ypred2022

array([743601.61594504])

# Lasso Regression

In [19]:
from sklearn.linear_model import Lasso

In [20]:
lasso=Lasso(alpha=1)
lasso.fit(x_train,y_train)
y_pred1=lasso.predict(x_test)

In [24]:
y_pred1

array([600774.90747294, 505558.59627394, 553166.75187345, 553166.75187345,
       553166.75187345, 410342.28507493, 505558.59627394, 553166.75187345,
       600774.90747294, 600774.90747294, 315125.97387594, 505558.59627394,
       410342.28507493, 648383.06307244, 553166.75187345, 600774.90747294,
       315125.97387594, 410342.28507493, 505558.59627394, 505558.59627394,
       505558.59627394, 505558.59627394, 505558.59627394])

In [25]:
mean_squared_error=np.mean((y_pred1 - y_test)**2)
print('Mean squared error on test set',mean_squared_error)

Mean squared error on test set 4326859771.015669


In [27]:
lasso_coeff=pd.DataFrame()
lasso_coeff['Columns']= x_train.columns
lasso_coeff['Coefficient Estimate']= pd.Series(lasso.coef_)
print(lasso_coeff)

  Columns  Coefficient Estimate
0    Year            47608.1556


In [28]:
#prdicting the possible price of a 2022
x_test2022= pd.DataFrame([2022],columns=['Year'])
y_predict2022=lasso.predict(x_test2022)

In [29]:
y_predict2022

array([743599.37427144])

In [30]:
#As the mse value is lesser lasso is little bit better.
#but there is no drastic difference between both.